### ISSUE TITLE
Comma and/or dot does not work on BQ

### ISSUE THREAD

**Issue by wood-galaxy** [mandel-macaque/chancho#99] opened 2015-04-11 09:14 UTC
Hi,
I can't enter comma or dot in any amount field.

BQ Aquaris E4.5 Ubuntu Edition
Ubuntu 14.10
Image number 20

**Comment by mandel-macaque** [comment] 2015-04-11 09:34
Hello! 

I do think that the comma or dot does work. I have been testing it with the bq phone and AFAIK everything is fine. Here is a video of it (sorry for the bad quality of the video)

https://www.youtube.com/watch?v=_fTme1ork1s

What might have been happening to you is that issue #84 where the input was not grabbed if you click the add button directly (it has been fixed in version 0.1.5 in the store already).

Please take it for a spin and confirm that this does not longer happens :)

**Comment by wood-galaxy** [comment] 2015-04-11 10:01
Hi thanks for your reply.
Unfortunately this does not work for me. I was already on the 0.1.5 version of Chancho. I have uninstall chancho then reinstall but it still the same.
A little off topic : do you know how to completely remove user data when uninstall ? i see that my account were still here after uninstall/reinstall. Perhaps it could help...

**Comment by mandel-macaque** [comment] 2015-04-11 10:13
Hm... the fact that you are french might be a very good tip. Let me test that, the double check is based on the locale and might be misbehaving with your locale.

To delete all data you have to rm the transactions database under ~/.local/share/chancho.mandel/ so the following will wipe all data and will get you to the wizard again:

rm ~/.local/share/chancho.mandel/

I have not added a hook to the click package to remove the data.. do you think that is a bug? I don't think so.. maybe people uninstall by mistake and they do not want to remove the db. What I can do is a special action in the "future" settings page to do it.

**Comment by wood-galaxy** [comment] 2015-04-11 10:14
Hey, I got it ! I have switch the langage to English (UK) and dot it's working !

**Comment by mandel-macaque** [comment] 2015-04-11 10:14
So it is the locale! Nice catch, will create a fix in a few mins and will release it!

**Comment by wood-galaxy** [comment] 2015-04-11 10:18
Nice ! Thank you.

About the data, I don't think it's a bug. Ubuntu work like that ! I think it's a feature request to the Ubuntu Store to let the user the choice to completely remove the data but since the Software center don't do that ... Let's see...
Thanks for the hint to remove local data.

**Comment by mandel-macaque** [comment] 2015-04-11 11:12
Fix merged. An other used translated the application to french, I'll merge the translation and will make the release.

**Comment by wood-galaxy** [comment] 2015-04-11 11:13
Cool, thank you for the work.

**Comment by mandel-macaque** [comment] 2015-04-11 13:33
The new version has been released, please let me know if the issue is fixed and will close it. Thx for the input!

**Comment by wood-galaxy** [comment] 2015-04-11 13:35
Awesome ! French language and dot ! Very cool ! It's working great. Thx

**Comment by mandel-macaque** [comment] 2015-04-11 15:50
Great! One bug less :)

**Closed by mandel-macaque** 2015-04-11 15:50 UTC
Labels: bug
